name: CI

on: [push]

jobs:
  # Running linting on Node 14 because of https://github.com/lo1tuma/eslint-plugin-mocha/issues/322
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - run: npm install -g npm@7
      - run: npm ci
      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14
          - 16
          - 18

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Node 14 still ships with npm@6 so for compatibility reasons we're upping this.
      - name: Install npm@8
        if: matrix.node-version == '14'
        run: npm install -g npm@7

      - run: npm ci
      - run: npm run test
